name: Playwright Tests

on:
    push:
        branches: [main] # запускается на пуш в main
    pull_request:
        branches: [main] # запускается на PR в main

jobs:
    test:
        runs-on: ubuntu-latest # среда выполнения

        steps:
            # 1️⃣ Клонируем репозиторий
            - uses: actions/checkout@v3

            # 2️⃣ Устанавливаем Node.js
            - uses: actions/setup-node@v3
              with:
                  node-version: 20

            # 3️⃣ Устанавливаем зависимости
            - run: npm ci

            # 4️⃣ Устанавливаем Playwright браузеры
            - run: npx playwright install --with-deps

            # 5️⃣ Запускаем все тесты с репортером Allure
            - run: npx playwright test --reporter=list,allure-playwright

            # 6️⃣ Генерируем HTML отчёт Allure
            - run: npx allure generate allure-results --clean

            # 7️⃣ Загружаем отчёт как артефакт Actions
            - uses: actions/upload-artifact@v4
              with:
                  name: allure-report
                  path: allure-report/
