name: Playwright Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # 1. Клонируем репозиторий
            - uses: actions/checkout@v3

            # 2. Устанавливаем Node.js
            - uses: actions/setup-node@v3
              with:
                  node-version: 20

            # 3. Устанавливаем зависимости
            - run: npm ci

            # 4. Устанавливаем Playwright браузеры
            - run: npx playwright install --with-deps

            # 5. Запускаем тесты только нужные файлы
            - run: npx playwright test tests/cud.spec.js tests/delete.spec.js --reporter=list,allure-playwright

            # 6. Генерируем Allure отчёт
            - run: npx allure generate allure-results --clean

            # 7. Загружаем отчёт как артефакт
            - uses: actions/upload-artifact@v4
              with:
                  name: allure-report
                  path: allure-report/
